name: nuplan
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=21.2.4
  - nb_conda_kernels
  - casadi
  - geopandas
  - pyogrio
  - grpcio  # Used for communication with submission container
  - grpcio-tools  # Used for communication with submission container
  - timm  # Used inc model_raster
  - pip:
    - -r requirements_torch.txt
    - -r requirements.txt
