name: nuplan-m1
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip=21.2.4
  - nb_conda_kernels
  - casadi
  - geopandas # Used to read maps
  - pyogrio # A performant backend for geopandas
  - grpcio  # Used for communication with submission container
  - grpcio-tools  # Used for communication with submission container
  - timm  # Used inc model_raster (pypi causes bus error on M1)
  - pytorch-lightning==1.3.8
  - torch
  - torchvision
  - torchaudio
  - torchmetrics==0.7.2
  - pip:
    - -r requirements.txt
